version: '2'

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - ./nextcloud/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpasshere
      - MYSQL_PASSWORD=databasepasswordhere
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: amd64/nextcloud
    links:
      - db
    volumes:
      - ./nextcloud/data:/var/www/html
    restart: always

  haproxy:
    image: jclebreton/https-proxy
    container_name: haproxy
    restart: always
    depends_on:
      - app
    links:
      - app
    environment:
      - BACKEND_SERVER=app
      - BACKEND_PORT=80
    ports:
      - 443:443
